import { Property } from "@/types/property"

export const mockProperties: Property[] = [
  {
    id: 1,
    name: "Campus View",
    address: "45 Merriman Ave",
    rent: 4500,
    deposit: 2000,
    nsfasAccredited: true,
    gas: null,
    water: null,
    electricity: null,
    about: "Modern student housing close to campus.",
    rules: "No smoking indoors.",
    landlordId: 12,
    suburb: "Central",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Oak Residence",
    address: "12 Dorp Street",
    rent: 3800,
    deposit: null,
    nsfasAccredited: false,
    gas: 50,
    water: 100,
    electricity: null,
    about: "Affordable student rooms.",
    rules: "Quiet hours after 10 PM.",
    landlordId: 15,
    suburb: "Oakdene",
    town: "Stellenbosch",
    genderRestriction: "FEMALE_ONLY",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Mountain View Lodge",
    address: "7 Victoria Street",
    rent: 5200,
    deposit: 2500,
    nsfasAccredited: true,
    gas: 20,
    water: 80,
    electricity: 120,
    about: "Spacious lodge with mountain views.",
    rules: "No pets allowed.",
    landlordId: 18,
    suburb: "Victoria",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Student Hub",
    address: "101 Bird Street",
    rent: 3000,
    deposit: 1500,
    nsfasAccredited: false,
    gas: null,
    water: 50,
    electricity: 75,
    about: "Budget-friendly student housing.",
    rules: "Shared kitchen, no loud music.",
    landlordId: 20,
    suburb: "Birdhaven",
    town: "Stellenbosch",
    genderRestriction: "MALE_ONLY",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Greenwood Flats",
    address: "22 Andringa Street",
    rent: 4100,
    deposit: 2000,
    nsfasAccredited: true,
    gas: 30,
    water: null,
    electricity: null,
    about: "Eco-friendly flats with solar panels.",
    rules: "Recycle bins must be used.",
    landlordId: 25,
    suburb: "Greenwood",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Riverside Apartments",
    address: "5 Mill Street",
    rent: 4700,
    deposit: 2200,
    nsfasAccredited: false,
    gas: null,
    water: 60,
    electricity: 90,
    about: "Close to river and park.",
    rules: "No loud parties.",
    landlordId: 30,
    suburb: "Riverside",
    town: "Stellenbosch",
    genderRestriction: "FEMALE_ONLY",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Sunset Villas",
    address: "88 Church Street",
    rent: 6000,
    deposit: 3000,
    nsfasAccredited: true,
    gas: 40,
    water: 70,
    electricity: 100,
    about: "Luxury villas with sunset views.",
    rules: "No smoking.",
    landlordId: 35,
    suburb: "Sunset",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Techie Residence",
    address: "33 Banhoek Road",
    rent: 3500,
    deposit: 1500,
    nsfasAccredited: false,
    gas: null,
    water: null,
    electricity: 80,
    about: "Affordable rooms for tech students.",
    rules: "Respect shared spaces.",
    landlordId: 40,
    suburb: "Banhoek",
    town: "Stellenbosch",
    genderRestriction: "MALE_ONLY",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Garden Cottages",
    address: "19 Plein Street",
    rent: 3900,
    deposit: 1800,
    nsfasAccredited: true,
    gas: 25,
    water: 60,
    electricity: null,
    about: "Cozy cottages with gardens.",
    rules: "Pets allowed.",
    landlordId: 45,
    suburb: "Garden",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: "City Center Rooms",
    address: "1 Andringa Street",
    rent: 2800,
    deposit: 1200,
    nsfasAccredited: false,
    gas: null,
    water: null,
    electricity: 50,
    about: "Rooms in the heart of the city.",
    rules: "No overnight guests.",
    landlordId: 50,
    suburb: "City Center",
    town: "Stellenbosch",
    genderRestriction: "FEMALE_ONLY",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
