import { Property } from "@/types/property";

export const mockProperties: Property[] = [
  {
    id: 1,
    name: "Campus View",
    address: "45 Merriman Ave",
    rent: 4500,
    deposit: 2000,
    nsfasAccredited: true,
    gas: null,
    water: null,
    electricity: null,
    about: "Modern student housing close to campus.",
    rules: "No smoking indoors.",
    landlordId: 12,
    suburb: "Central",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 1, name: "WiFi", propertyId: 1 },
      { id: 2, name: "Parking", propertyId: 1 },
    ],
    comments: [
      { id: 1, content: "Great location near campus!", rating: 5, commenterId: 101, propertyId: 1 },
      { id: 2, content: "Rooms are spacious and clean.", rating: 4, commenterId: 102, propertyId: 1 },
    ],
  },
  {
    id: 2,
    name: "Oak Residence",
    address: "12 Dorp Street",
    rent: 3800,
    deposit: null,
    nsfasAccredited: false,
    gas: 50,
    water: 100,
    electricity: null,
    about: "Affordable student rooms.",
    rules: "Quiet hours after 10 PM.",
    landlordId: 15,
    suburb: "Oakdene",
    town: "Stellenbosch",
    genderRestriction: "FEMALE_ONLY",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 3, name: "Study Room", propertyId: 2 },
      { id: 4, name: "Laundry", propertyId: 2 },
    ],
    comments: [
      { id: 3, content: "Affordable and cozy.", rating: 4, commenterId: 103, propertyId: 2 },
    ],
  },
  {
    id: 3,
    name: "Mountain View Lodge",
    address: "7 Victoria Street",
    rent: 5200,
    deposit: 2500,
    nsfasAccredited: true,
    gas: 20,
    water: 80,
    electricity: 120,
    about: "Spacious lodge with mountain views.",
    rules: "No pets allowed.",
    landlordId: 18,
    suburb: "Victoria",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 5, name: "WiFi", propertyId: 3 },
      { id: 6, name: "Parking", propertyId: 3 },
      { id: 7, name: "Laundry", propertyId: 3 },
    ],
    comments: [
      { id: 4, content: "Amazing views!", rating: 5, commenterId: 104, propertyId: 3 },
    ],
  },
  {
    id: 4,
    name: "Student Hub",
    address: "101 Bird Street",
    rent: 3000,
    deposit: 1500,
    nsfasAccredited: false,
    gas: null,
    water: 50,
    electricity: 75,
    about: "Budget-friendly student housing.",
    rules: "Shared kitchen, no loud music.",
    landlordId: 20,
    suburb: "Birdhaven",
    town: "Stellenbosch",
    genderRestriction: "MALE_ONLY",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 8, name: "Study Room", propertyId: 4 },
    ],
    comments: [
      { id: 5, content: "Good for budget living.", rating: 3, commenterId: 105, propertyId: 4 },
    ],
  },
  {
    id: 5,
    name: "Greenwood Flats",
    address: "22 Andringa Street",
    rent: 4100,
    deposit: 2000,
    nsfasAccredited: true,
    gas: 30,
    water: null,
    electricity: null,
    about: "Eco-friendly flats with solar panels.",
    rules: "Recycle bins must be used.",
    landlordId: 25,
    suburb: "Greenwood",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 9, name: "WiFi", propertyId: 5 },
      { id: 10, name: "Parking", propertyId: 5 },
    ],
    comments: [
      { id: 6, content: "Love the eco-friendly vibe.", rating: 5, commenterId: 106, propertyId: 5 },
    ],
  },
  {
    id: 6,
    name: "Riverside Apartments",
    address: "5 Mill Street",
    rent: 4700,
    deposit: 2200,
    nsfasAccredited: false,
    gas: null,
    water: 60,
    electricity: 90,
    about: "Close to river and park.",
    rules: "No loud parties.",
    landlordId: 30,
    suburb: "Riverside",
    town: "Stellenbosch",
    genderRestriction: "FEMALE_ONLY",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 11, name: "Laundry", propertyId: 6 },
    ],
    comments: [
      { id: 7, content: "Peaceful environment.", rating: 4, commenterId: 107, propertyId: 6 },
    ],
  },
  {
    id: 7,
    name: "Sunset Villas",
    address: "88 Church Street",
    rent: 6000,
    deposit: 3000,
    nsfasAccredited: true,
    gas: 40,
    water: 70,
    electricity: 100,
    about: "Luxury villas with sunset views.",
    rules: "No smoking.",
    landlordId: 35,
    suburb: "Sunset",
    town: "Stellenbosch",
    genderRestriction: "MIXED",
    propertyType: "SINGLE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 12, name: "WiFi", propertyId: 7 },
      { id: 13, name: "Parking", propertyId: 7 },
    ],
    comments: [
      { id: 8, content: "Beautiful sunsets every evening.", rating: 5, commenterId: 108, propertyId: 7 },
    ],
  },
  {
    id: 8,
    name: "Techie Residence",
    address: "33 Banhoek Road",
    rent: 3500,
    deposit: 1500,
    nsfasAccredited: false,
    gas: null,
    water: null,
    electricity: 80,
    about: "Affordable rooms for tech students.",
    rules: "Respect shared spaces.",
    landlordId: 40,
    suburb: "Banhoek",
    town: "Stellenbosch",
    genderRestriction: "MALE_ONLY",
    propertyType: "SHARING",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    amenities: [
      { id: 14, name: "Study Room", propertyId: 8 },
    ],
    comments: [
      { id: 9, content: "Perfect for techies.", rating: 4, commenterId: 109, propertyId: 8 },
    ],
  }]