import {
  Wifi,
  Zap,
  ShieldCheck,
  Droplets,
  Car,
  Utensils,
  WashingMachine,
  Wind,
  Bus,
  // 🔒 Security icons
  Camera,
  Shield,
  Bell,
  Lock,
  Fingerprint,
  DoorClosed,
  UserCheck,
  // ⚡ Loadshedding icons
  Battery,
  Flame,
  Sun,
  GraduationCap,
  ShoppingCart,
  ShoppingBag,
  BookOpen,
  Train,
  Dumbbell,
  Hospital,
  Coffee,
} from "lucide-react"
export const amenitiesList = [
  { id: "wifi", label: "WiFi", icon: Wifi },
  { id: "prepaid", label: "Prepaid Electricity", icon: Zap },
  { id: "security", label: "24/7 Security", icon: ShieldCheck },
  { id: "water", label: "Water Included", icon: Droplets },
  { id: "parking", label: "Parking", icon: Car },
  { id: "kitchen", label: "Shared Kitchen", icon: Utensils },
  { id: "laundry", label: "Laundry", icon: WashingMachine },
  { id: "aircon", label: "Air Conditioning", icon: Wind },
  { id: "shuttle", label: "Shuttle", icon: Bus },

  // 🔒 Security extras
  { id: "electric-fence", label: "Electric Fence", icon: Zap },
  { id: "cctv", label: "CCTV", icon: Camera },
  { id: "armed-response", label: "Armed Response", icon: Shield },
  { id: "security-guard", label: "Security Guard", icon: UserCheck },
  { id: "alarm-system", label: "Alarm System", icon: Bell },
  { id: "security-bars", label: "Security Bars", icon: Lock },
  { id: "biometric-access", label: "Biometric Access", icon: Fingerprint },
  { id: "security-gate", label: "Security Gate", icon: DoorClosed },

  // ⚡ Loadshedding extras
  { id: "inverter", label: "Inverter", icon: Battery },
  { id: "gas", label: "Gas", icon: Flame },
  { id: "solar", label: "Solar", icon: Sun },
  { id: "generator", label: "Generator", icon: Zap },
]
export const placeTypes = [
  { value: "university", label: "University / College", icon: GraduationCap },
  { value: "shop", label: "Shop / Supermarket", icon: ShoppingCart },
  { value: "mall", label: "Mall", icon: ShoppingBag },
  { value: "library", label: "Library", icon: BookOpen },
  { value: "bus", label: "Bus / Taxi Stop", icon: Bus },
  { value: "train", label: "Train / Gautrain", icon: Train },
  { value: "gym", label: "Gym", icon: Dumbbell },
  { value: "hospital", label: "Hospital / Clinic", icon: Hospital },
  { value: "restaurant", label: "Restaurant / Cafe", icon: Coffee },
]
