// South African provinces and towns
// Source: compiled from Wikipedia's list of populated places in South Africa

export const provinces = [
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "Northern Cape",
  "North West",
  "Western Cape",
] as const

export type Province = (typeof provinces)[number]

export const townsByProvince: Record<Province, string[]> = {
  "Eastern Cape": [
    "Aberdeen",
    "Addo",
    "Adelaide",
    "Adendorp",
    "Alderley",
    "Alexandria",
    "Alice",
    "Alicedale",
    "Aliwal North",
    "Bailey",
    "Balfour",
    "Barakke",
    "Barkly East",
    "Baroe",
    "Bathurst",
    "Bedford",
    "Behulpsaam",
    "Bell",
    "Bellevue",
    "Berlin",
    "Bethelsdorp",
    "Bhisho",
    "Bityi",
    "Bluewater Bay",
    "Bonza Bay",
    "Braunschweig",
    "Burgersdorp",
    "Butterworth",
    "Cala",
    "Cambria",
    "Cannon Rocks",
    "Cape St. Francis",
    "Cathcart",
    "Chalumna",
    "Chintsa",
    "Clarkebury",
    "Clifford",
    "Coega",
    "Coffee Bay",
    "Cofimvaba",
    "Coghlan",
    "Colchester",
    "Coleford",
    "Cookhouse",
    "Cradock",
    "Despatch",
    "Dordrecht",
    "Dutywa",
    "Döhne",
    "East London",
    "Elliot",
    "Engcobo",
    "Flagstaff",
    "Fort Beaufort",
    "Gcuwa",
    "Gonubie",
    "Graaff-Reinet",
    "Grahamstown",
    "Hankey",
    "Hofmeyr",
    "Humansdorp",
    "Ibhayi",
    "Indwe",
    "Jansenville",
    "Jeffreys Bay",
    "Kenton-on-Sea",
    "King William's Town",
    "Kirkwood",
    "Lady Frere",
    "Lady Grey",
    "Maclear",
    "Matatiele",
    "Middelburg",
    "Molteno",
    "Mount Fletcher",
    "Mthatha",
    "Nieu-Bethesda",
    "Oyster Bay",
    "Patensie",
    "Paterson",
    "Port Alfred",
    "Port Elizabeth",
    "Port St. Johns",
    "Queenstown",
    "Somerset East",
    "St Francis Bay",
    "St Georges Strand",
    "Steynsburg",
    "Stutterheim",
    "Summerstrand",
    "Swartkops",
    "Tarkastad",
    "Uitenhage",
    "Whittlesea",
    "Zwelitsha",
  ],
  "Free State": [
    "Aberfeldy",
    "Allandale",
    "Allanridge",
    "Allep",
    "Arlington",
    "Bethlehem",
    "Bethulie",
    "Bloemfontein",
    "Boompie Alleen",
    "Boshof",
    "Bothaville",
    "Botshabelo",
    "Brandfort",
    "Bultfontein",
    "Clarens",
    "Clocolan",
    "Cornelia",
    "Dealesville",
    "Deneysville",
    "Dewetsdorp",
    "Edenburg",
    "Edenville",
    "Excelsior",
    "Fauresmith",
    "Ficksburg",
    "Fouriesburg",
    "Frankfort",
    "Harrismith",
    "Heilbron",
    "Hennenman",
    "Hertzogville",
    "Hobhouse",
    "Hoopstad",
    "Jacobsdal",
    "Jagersfontein",
    "Kestell",
    "Kgotsong",
    "Koffiefontein",
    "Koppies",
    "Kroonstad",
    "Ladybrand",
    "Lindley",
    "Luckhoff",
    "Makeleketla",
    "Marquard",
    "Memel",
    "Odendaalsrus",
    "Oranjeville",
    "Parys",
    "Paul Roux",
    "Petrus Steyn",
    "Petrusburg",
    "Philippolis",
    "Phuthaditjhaba",
    "Reddersburg",
    "Reitz",
    "Rosendal",
    "Rouxville",
    "Sasolburg",
    "Senekal",
    "Smithfield",
    "Springfontein",
    "Steynsrus",
    "Swinburne",
    "Thaba Nchu",
    "Theunissen",
    "Trompsburg",
    "Tweeling",
    "Tweespruit",
    "Van Stadensrus",
    "Ventersburg",
    "Verkeerdevlei",
    "Viljoenskroon",
    "Villiers",
    "Vrede",
    "Vredefort",
    "Warden",
    "Welkom",
    "Wepener",
    "Wesselsbron",
    "Winburg",
    "Zastron",
  ],
  Gauteng: [
    "Akasia",
    "Alberton",
    "Alexandra",
    "Atteridgeville",
    "Bank",
    "Bapsfontein",
    "Benoni",
    "Boipatong",
    "Boksburg",
    "Bophelong",
    "Brakpan",
    "Bronkhorstspruit",
    "Carletonville",
    "Centurion",
    "Chantelle",
    "Cullinan",
    "Daveyton",
    "Devon",
    "Duduza",
    "Edenvale",
    "Evaton",
    "Fochville",
    "Germiston",
    "Hammanskraal",
    "Heidelberg",
    "Henley on Klip",
    "Irene",
    "Isando",
    "Johannesburg",
    "Katlehong",
    "Kempton Park",
    "Kromdraai",
    "Krugersdorp",
    "KwaThema",
    "Lenasia",
    "Lyttelton",
    "Magaliesburg",
    "Mamelodi",
    "Meyerton",
    "Midrand",
    "Muldersdrift",
    "Nigel",
    "Orchards",
    "Pretoria",
    "Randburg",
    "Randfontein",
    "Ratanda",
    "Roodepoort",
    "Rooihuiskraal",
    "Sandton",
    "Sebokeng",
    "Sharpeville",
    "Soshanguve",
    "Soweto",
    "Springs",
    "Tembisa",
    "Thokoza",
    "Tsakane",
    "Vanderbijlpark",
    "Vereeniging",
    "Vosloorus",
    "Wedela",
    "Westonaria",
  ],
  "KwaZulu-Natal": [
    "Ahrens",
    "Amahlongwa",
    "Amandawe",
    "Amanzimtoti",
    "Anerley",
    "Babanango",
    "Balgowan",
    "Ballengeich",
    "Ballito",
    "Bazley",
    "Bergville",
    "Besters",
    "Biggarsberg",
    "Boboyi",
    "Boston",
    "Bulwer",
    "Calvert",
    "Camperdown",
    "Candover",
    "Cape Vidal",
    "Catalina Bay",
    "Cato Ridge",
    "Cedarville",
    "Charlestown",
    "Clansthal",
    "Clermont",
    "Colenso",
    "Craigieburn",
    "Dalton",
    "Dannhauser",
    "Darnall",
    "Doonside",
    "Drummond",
    "Dududu",
    "Dundee",
    "Durban",
    "Elandslaagte",
    "Empangeni",
    "Eshowe",
    "Estcourt",
    "Franklin",
    "Glencoe",
    "Greytown",
    "Harding",
    "Hattingspruit",
    "Hibberdene",
    "Hillcrest",
    "Hilton",
    "Himeville",
    "Hluhluwe",
    "Howick",
    "Ifafa Beach",
    "Illovo Beach",
    "Impendle",
    "Inanda",
    "Ingwavuma",
    "Isipingo",
    "Ixopo",
    "Izingolweni",
    "Karridene",
    "Kingsburgh",
    "Kloof",
    "Kokstad",
    "KwaCele",
    "KwaDukuza",
    "KwaMashu",
    "La Lucia",
    "La Mercy",
    "Ladysmith",
    "Louwsburg",
    "Madadeni",
    "Magabeni",
    "Mahlabatini",
    "Mandini",
    "Margate",
    "Mathulini",
    "Melmoth",
    "Melville",
    "Merrivale",
    "Mkuze",
    "Mooirivier",
    "Mount Edgecombe",
    "Mthwalume",
    "Mtubatuba",
    "Mtunzini",
    "Muden",
    "Murchison",
    "New Germany",
    "New Hanover",
    "Newcastle",
    "Nongoma",
    "Nottingham Road",
    "Nquthu",
    "Palm Beach",
    "Park Rynie",
    "Paulpietersburg",
    "Pennington",
    "Pietermaritzburg",
    "Pinetown",
    "Pomeroy",
    "Pongola",
    "Port Edward",
    "Port Shepstone",
    "Queensburgh",
    "Ramsgate",
    "Richards Bay",
    "Salt Rock",
    "Scottburgh",
    "Sezela",
    "Shakaskraal",
    "Shelly Beach",
    "Southbroom",
    "St Lucia",
    "St Michael's-on-sea",
    "St. Faith's",
    "Tinley Manor Beach",
    "Tugela Ferry",
    "Ubombo",
    "Ulundi",
    "Umbogintwini",
    "Umgababa",
    "Umhlali",
    "Umkomaas",
    "Umlazi",
    "Umtentweni",
    "Umzimkhulu",
    "Umzinto",
    "Umzumbe",
    "Underberg",
    "Utrecht",
    "Uvongo",
    "Van Reenen",
    "Verulam",
    "Virginia",
    "Vryheid",
    "Warner Beach",
    "Wartburg",
    "Wasbank",
    "Waterfall",
    "Weenen",
    "Westville",
    "Winkelspruit",
    "Winterton",
    "York",
    "eMdloti",
    "ekuPhakameni",
    "oThongathi",
    "uMhlanga",
  ],
  Limpopo: [
    "Alldays",
    "Baltimore",
    "Bandelierkop",
    "Bandur",
    "Beauty",
    "Beitbridge",
    "Bela-Bela",
    "Burgersfort",
    "Carlow",
    "Chuniespoort",
    "Duiwelskloof",
    "Ga-Motlagomo",
    "Giyani",
    "Gravelotte",
    "Groblersdal",
    "Haenertsburg",
    "Hoedspruit",
    "Lephalale",
    "Louis Trichardt",
    "Marble Hall",
    "Modimolle",
    "Mokopane",
    "Musina",
    "Naboomspruit",
    "Phalaborwa",
    "Polokwane",
    "Shawela",
    "Thabazimbi",
    "Thohoyandou",
    "Vaalwater",
    "Vivo",
  ],
  Mpumalanga: [
    "Acornhoek",
    "Amersfoort",
    "Amsterdam",
    "Badplaas",
    "Balfour",
    "Balmoral",
    "Bankkop",
    "Barberton",
    "Belfast",
    "Berbice",
    "Bethal",
    "Bettiesdam",
    "Bosbokrand",
    "Breyten",
    "Carolina",
    "Charl Cilliers",
    "Chrissiesmeer",
    "Clewer",
    "Coalville",
    "Commondale",
    "Cork",
    "Delmas",
    "Dullstroom",
    "Ermelo",
    "Graskop",
    "Greylingstad",
    "Hazyview",
    "Hectorspruit",
    "Kaapmuiden",
    "Kinross",
    "Komatipoort",
    "Kriel",
    "KwaMhlanga",
    "Loopspruit",
    "Lydenburg",
    "Machadodorp",
    "Malelane",
    "Mbombela",
    "Middelburg",
    "Morgenzon",
    "Ogies",
    "Ohrigstad",
    "Perdekop",
    "Piet Retief",
    "Pilgrim's Rest",
    "Sabie",
    "Secunda",
    "Standerton",
    "Trichardt",
    "Vaalbank",
    "Volksrust",
    "Wakkerstroom",
    "Waterval Boven",
    "Waterval Onder",
    "White River",
    "Witbank",
  ],
  "Northern Cape": [
    "Aggeneys",
    "Alexander Bay",
    "Askham",
    "Augrabies",
    "Barkly West",
    "Bekker",
    "Belmont",
    "Bermolli",
    "Biesiespoort",
    "Britstown",
    "Calvinia",
    "Campbell",
    "Carlton",
    "Carnarvon",
    "Carolusberg",
    "Colesberg",
    "Colston",
    "Concordia",
    "Copperton",
    "Danielskuil",
    "De Aar",
    "Delportshoop",
    "Dibeng",
    "Dingleton",
    "Douglas",
    "Fraserburg",
    "Griekwastad",
    "Groblershoop",
    "Hopetown",
    "Jan Kempdorp",
    "Kimberley",
    "Modder River",
    "Orania",
    "Plooysburg",
    "Prieska",
    "Richmond",
    "Springbok",
    "Strydenburg",
    "Upington",
    "Victoria West",
    "Warrenton",
    "Williston",
  ],
  "North West": [
    "Albertshoek",
    "Alettasrus",
    "Amalia",
    "Babelegi",
    "Bakerville",
    "Barberspan",
    "Beestekraal",
    "Bethanie",
    "Bewley",
    "Biesiesvlei",
    "Bloemhof",
    "Bray",
    "Brits",
    "Broederstroom",
    "Carlsonia",
    "Christiana",
    "Coligny",
    "Delareyville",
    "Derby",
    "Ga-Rankuwa",
    "Ganyesa",
    "Groot Marico",
    "Hartbeespoort",
    "Klerksdorp",
    "Lichtenburg",
    "Mafikeng",
    "Mmabatho",
    "Orkney",
    "Potchefstroom",
    "Rustenburg",
    "Sannieshof",
    "Schweizer-Reneke",
    "Stilfontein",
    "Vryburg",
    "Wolmaransstad",
    "Zeerust",
  ],
  "Western Cape": [
    "Aan de Doorns",
    "Abbotsdale",
    "Albertinia",
    "Amalienstein",
    "Arniston",
    "Ashton",
    "Atlantis",
    "Aurora",
    "Baardskeerdersbos",
    "Barrington",
    "Barrydale",
    "Baviaan",
    "Beaufort West",
    "Bellville",
    "Berea",
    "Bergplaas",
    "Bergrivier",
    "Betty's Bay",
    "Biesiesfontein",
    "Bitterfontein",
    "Blouberg",
    "Bonnievale",
    "Brackenfell",
    "Bredasdorp",
    "Buffelsjagbaai",
    "Caledon",
    "Calitzdorp",
    "Camps Bay",
    "Cape Town",
    "Ceres",
    "Churchaven",
    "Citrusdal",
    "Clanwilliam",
    "Claremont",
    "Clarkson",
    "Clifton",
    "Constantia",
    "Darling",
    "De Doorns",
    "De Kelders",
    "De Rust",
    "Doringbaai",
    "Durbanville",
    "Dysselsdorp",
    "Eendekuil",
    "Elandsbaai",
    "Elgin",
    "Elim",
    "Faure",
    "Firgrove",
    "Fish Hoek",
    "Fisherhaven",
    "Franschhoek",
    "Franskraal",
    "Gansbaai",
    "Genadendal",
    "George",
    "Gordon's Bay",
    "Gouda",
    "Graafwater",
    "Grabouw",
    "Greyton",
    "Heidelberg",
    "Hermanus",
    "Hopefield",
    "Jamestown",
    "Keurboomstrand",
    "Khayelitsha",
    "Klapmuts",
    "Knysna",
    "Kommetjie",
    "Kraaifontein",
    "Kuils River",
    "L'Agulhas or Agulhas",
    "Laingsburg",
    "Lambert's Bay",
    "Matjiesfontein",
    "Melkbosstrand",
    "Melkhoutfontein",
    "Milnerton",
    "Mossel Bay",
    "Muizenberg",
    "Noordhoek",
    "Oudtshoorn",
    "Paarl",
    "Philadelphia",
    "Piketberg",
    "Plettenberg Bay",
    "Pniel",
    "Prins Albert",
    "Riebeek Kasteel",
    "Robertson",
    "Somerset West",
    "Stellenbosch",
    "Strand",
    "Swartberg",
    "Swellendam",
    "Tulbagh",
    "Uniondale",
    "Wellington",
    "Wilderness",
    "Worcester",
    "Yzerfontein",
  ],
}

export const allTowns: string[] = Object.values(townsByProvince).flat()
